version: '3'
services:
  db:
    image: mariadb:jammy
    container_name: db
    env_file:
      - mysql.env # configure env vars in this file
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql # Persist data even if container shuts down
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8080:80
volumes:
  dbdata: