version: '3.7'
services:
  postgres:
    image: postgres:latest
    env_file:
      - db.env # configure env vars in this file
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data/ # Persist data even if container shuts down

volumes:
  postgres-data: